parameters:
#    application_admin.example.class: Application\AdminBundle\Example

services:
#    application_admin.example:
#        class: %application_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    application_admin.admin.category:
        class: Application\AdminBundle\Admin\CategoryAdmin
        arguments: [~, Application\AdminBundle\Entity\Category, ApplicationAdminBundle:CategoryAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Category}
