application_fos_message:
    resource: "@ApplicationFOSMessageBundle/Resources/config/routing.yml"
    prefix: /

application_sonata_user:
    resource: "@ApplicationSonataUserBundle/Resources/config/routing.yml"
    prefix:   /

application_admin:
    resource: "@ApplicationAdminBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin
 
_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

fos_message:
    resource: "@FOSMessageBundle/Resources/config/routing.xml"
    prefix: /admin/message