## YAML Template.
---
#services:
#    application.sonata.admin.category:
#        class: Application\Sonata\AdminBundle\Admin\CategoryAdmin
#        tags:
#            - { name: sonata.admin, manager_type: orm, group: jobeet, label: Categories }
#        arguments:
#            - ~
#            - Ibw\JobeetBundle\Entity\Category
#            - 'IbwJobeetBundle:CategoryAdmin'
 
#    ibw.jobeet.admin.job:
#        class: Ibw\JobeetBundle\Admin\JobAdmin
#        tags:
#            - { name: sonata.admin, manager_type: orm, group: jobeet, label: Jobs }
#        arguments:
#            - ~
#            - Ibw\JobeetBundle\Entity\Job
#            - 'IbwJobeetBundle:JobAdmin'