sonata_notification:
    backend: sonata.notification.backend.runtime
    backend: sonata.notification.backend.doctrine

#    consumer:
#                swift_mailer:
#                    path:         %kernel.root_dir%/../vendor/swiftmailer
    backends:
            doctrine:
                message_manager: sonata.notification.manager.message.default
#                message_manager: sonata.notification.manager.message.mailer
                max_age:         86400     # max age in second
                pause:           500000    # delay in microseconds
                states:                    # raising errors level
                    in_progress: 10
                    error:       20
                    open:        100
                    done:        10000
#    consumer:
#            swift_mailer:
#                path:         %kernel.root_dir%/../vendor/swiftmailer
#        backends:
#            doctrine:
#                message_manager: sonata.notification.manager.message.mailer

doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    SonataNotificationBundle: ~
#                    ApplicationSonataNotificationBundle: ~