sonata_user:
    security_acl: true
    manager_type: orm
    class:                  # Entity Classes
             user:               Application\Sonata\UserBundle\Entity\User
             group:              Application\Sonata\UserBundle\Entity\Group
